### ISSUE TITLE
New beta version (1.9.0) crashes after login

### ISSUE THREAD

**Issue by aisuneko** [zend10/AL-chan#106]
After login, Beta 1.9.0 will always crash immediately on app launch. `logcat` shows this:
```
11-12 23:44:11.857 E/com.zen.alchan(14970): Invalid ID 0x00000000.
11-12 23:44:11.886 E/com.zen.alchan(14970): Invalid ID 0x00000000.
11-12 23:44:12.213 E/AndroidRuntime(14970): FATAL EXCEPTION: main
11-12 23:44:12.213 E/AndroidRuntime(14970): Process: com.zen.alchan, PID: 14970
11-12 23:44:12.213 E/AndroidRuntime(14970): io.reactivex.exceptions.CompositeException: 2 exceptions occurred. 
11-12 23:44:12.213 E/AndroidRuntime(14970): 	at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:80)
11-12 23:44:12.213 E/AndroidRuntime(14970): 	at io.reactivex.internal.operators.observable.ObservableDoFinally$DoFinallyObserver.onError(ObservableDoFinally.java:85)
11-12 23:44:12.213 E/AndroidRuntime(14970): 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:281)
11-12 23:44:12.213 E/AndroidRuntime(14970): 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
11-12 23:44:12.213 E/AndroidRuntime(14970): 	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
11-12 23:44:12.213 E/AndroidRuntime(14970): 	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
11-12 23:44:12.213 E/AndroidRuntime(14970): 	at android.os.Handler.handleCallback(Handler.java:938)
11-12 23:44:12.213 E/AndroidRuntime(14970): 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-12 23:44:12.213 E/AndroidRuntime(14970): 	at android.os.Looper.loopOnce(Looper.java:201)
11-12 23:44:12.213 E/AndroidRuntime(14970): 	at android.os.Looper.loop(Looper.java:288)
11-12 23:44:12.213 E/AndroidRuntime(14970): 	at android.app.ActivityThread.main(ActivityThread.java:7870)
11-12 23:44:12.213 E/AndroidRuntime(14970): 	at java.lang.reflect.Method.invoke(Native Method)
11-12 23:44:12.213 E/AndroidRuntime(14970): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
11-12 23:44:12.213 E/AndroidRuntime(14970): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
11-12 23:44:12.213 E/AndroidRuntime(14970):   ComposedException 1 :
11-12 23:44:12.213 E/AndroidRuntime(14970): 	com.apollographql.apollo.exception.ApolloHttpException: HTTP 429 
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor.parse(ApolloParseInterceptor.java:108)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at com.apollographql.apollo.internal.interceptor.ApolloParseInterceptor$1.onResponse(ApolloParseInterceptor.java:53)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at com.apollographql.apollo.internal.interceptor.ApolloServerInterceptor$executeHttpCall$1.onResponse(ApolloServerInterceptor.kt:110)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at java.lang.Thread.run(Thread.java:920)
11-12 23:44:12.213 E/AndroidRuntime(14970): 	Caused by: com.zen.alchan.helper.utils.NotInStorageException
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at com.zen.alchan.data.repository.DefaultMediaListRepository.getMediaListCollection(DefaultMediaListRepository.kt:95)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at com.zen.alchan.ui.medialist.MediaListViewModel.getMediaListCollectionFromCache(MediaListViewModel.kt:371)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at com.zen.alchan.ui.medialist.MediaListViewModel.getMediaListCollection$lambda-9(MediaListViewModel.kt:360)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at com.zen.alchan.ui.medialist.MediaListViewModel.$r8$lambda$i8dWZ1oRzfDm1ltLOHfHTqQAqPI(Unknown Source:0)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at com.zen.alchan.ui.medialist.MediaListViewModel$$ExternalSyntheticLambda10.accept(Unknown Source:4)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at io.reactivex.internal.operators.observable.ObservableDoFinally$DoFinallyObserver.onError(ObservableDoFinally.java:85)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:281)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at android.os.Handler.handleCallback(Handler.java:938)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at android.os.Handler.dispatchMessage(Handler.java:99)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at android.os.Looper.loopOnce(Looper.java:201)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at android.os.Looper.loop(Looper.java:288)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at android.app.ActivityThread.main(ActivityThread.java:7870)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at java.lang.reflect.Method.invoke(Native Method)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
11-12 23:44:12.213 E/AndroidRuntime(14970):   ComposedException 2 :
11-12 23:44:12.213 E/AndroidRuntime(14970): 	com.zen.alchan.helper.utils.NotInStorageException
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at com.zen.alchan.data.repository.DefaultMediaListRepository.getMediaListCollection(DefaultMediaListRepository.kt:95)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at com.zen.alchan.ui.medialist.MediaListViewModel.getMediaListCollectionFromCache(MediaListViewModel.kt:371)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at com.zen.alchan.ui.medialist.MediaListViewModel.getMediaListCollection$lambda-9(MediaListViewModel.kt:360)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at com.zen.alchan.ui.medialist.MediaListViewModel.$r8$lambda$i8dWZ1oRzfDm1ltLOHfHTqQAqPI(Unknown Source:0)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at com.zen.alchan.ui.medialist.MediaListViewModel$$ExternalSyntheticLambda10.accept(Unknown Source:4)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at io.reactivex.internal.operators.observable.ObservableDoFinally$DoFinallyObserver.onError(ObservableDoFinally.java:85)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:281)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at android.os.Handler.handleCallback(Handler.java:938)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at android.os.Handler.dispatchMessage(Handler.java:99)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at android.os.Looper.loopOnce(Looper.java:201)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at android.os.Looper.loop(Looper.java:288)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at android.app.ActivityThread.main(ActivityThread.java:7870)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at java.lang.reflect.Method.invoke(Native Method)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
11-12 23:44:12.213 E/AndroidRuntime(14970): 		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```
I'm using LineageOS 19.1 (Android 12). Is it a network issue or so?

**Comment by imashnake0** [comment]
Anilist's API is down, see #105. They are accepting around 5 requests every second hence the 429.

**Comment by zend10** [comment]
Found this bug thanks to the API being down.
