### ISSUE TITLE
Out of memory exceptions while trying to use the Android app

### ISSUE THREAD

**Issue by kuru-rin** [zend10/AL-chan#114]
Sadly I can no longer use the Android app since I am getting out of memory exceptions all the time.
I believe it is when I do something concerning my list (even when just pushing `Add to planning` buttons).

I have tried normal and beta versions from Play Store.

My assumption is that my list is larger than average and it tries to load it in the memory completely?
https://anilist.co/user/Kururin/animelist

My phone is definitely not out of memory, so it is some Android limitation perhaps? I couldn't really find anyway way to increase the memory limit for an individual app.

Exception:
```
w9.e: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | 
java.lang.OutOfMemoryError: Failed to allocate a 150994952 byte allocation with 8388608 free bytes and 140MB until OOM, target footprint 129382792, growth limit 268435456
	at na.a.a(SourceFile:46)
	at da.c$a.b(Unknown Source:4)
	at kotlinx.coroutines.reactive.g.m0(SourceFile:108)
	at kotlinx.coroutines.reactive.f.n(Unknown Source:11)
	at wa.a.k(SourceFile:9)
	at kotlinx.coroutines.internal.q.i0(Unknown Source:6)
	at kb.a.k(SourceFile:23)
	at wa.a.k(SourceFile:32)
	at kb.i0.run(Unknown Source:100)
	at u9.m$a.run(Unknown Source:9)
	at ha.i.run(Unknown Source:21)
	at ha.i.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 150994952 byte allocation with 8388608 free bytes and 140MB until OOM, target footprint 129382792, growth limit 268435456
	at java.util.Arrays.copyOf(Arrays.java:3766)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:650)
	at java.lang.StringBuffer.append(StringBuffer.java:381)
	at java.io.StringWriter.write(StringWriter.java:77)
	at x5.c.Q(Unknown Source:13)
	at x5.c.Z(Unknown Source:12)
	at t5.q$f.b(SourceFile:3)
	at t5.p.b(SourceFile:49)
	at t5.m.b(SourceFile:26)
	at t5.n$a.b(Unknown Source:42)
	at t5.p.b(SourceFile:49)
	at t5.b$a.b(SourceFile:28)
	at t5.p.b(SourceFile:49)
	at t5.m.b(SourceFile:26)
	at t5.n$a.b(Unknown Source:42)
	at q5.i$a.b(Unknown Source:4)
	at t5.p.b(SourceFile:49)
	at t5.m.b(SourceFile:26)
	at t5.n$a.b(Unknown Source:42)
	at t5.p.b(SourceFile:49)
	at t5.b$a.b(SourceFile:28)
	at t5.p.b(SourceFile:49)
	at t5.m.b(SourceFile:26)
	at t5.n$a.b(Unknown Source:42)
	at t5.p.b(SourceFile:49)
	at t5.b$a.b(SourceFile:28)
	at t5.p.b(SourceFile:49)
	at t5.m.b(SourceFile:26)
	at t5.n$a.b(Unknown Source:42)
	at t5.l.b(SourceFile:36)
	at t5.p.b(SourceFile:49)
	at t5.m.b(SourceFile:26)
	at t5.n$a.b(Unknown Source:42)
	at q5.i.h(SourceFile:29)
	at q5.i.g(SourceFile:42)
	at p6.f.f(Unknown Source:2)
	at q6.e.f(Unknown Source:2)
	at v6.d0$b.apply(SourceFile:1387)
	at ea.p$a.d(SourceFile:10)
	at fa.h$a.e(Unknown Source:28)
	at da.c$a.d(Unknown Source:27)
	at kotlinx.coroutines.reactive.c.c(SourceFile:5)
	at androidx.activity.o.y(SourceFile:141)
	at nb.d.n(SourceFile:12)
	at wa.a.k(SourceFile:9)
	... 9 more
```

It would be really great if this could be fixed somehow, or perhaps there is a workaround after all?

Also let me thank you anyway for all the time that I was able to use this great app. :)

**Comment by zend10** [comment]
I imported your list and use the Beta app to test this. Seems like it works fine on some device and completely broken on others.

I'm no longer maintaining the non-Beta app, so I'll only fix it for the Beta version. Do you remember when you are trying with the Beta app: Did it crash directly without ever completely loading the list or did it manage to load the list and only crashed when there's an update? From my test, it should crash without ever fully loading the list.

If it crashed without ever fully loading the list, I guess I've figured out the issue. I've found that the crash is happening because of the caching file size that reach 40MB (yes, wild). I think it can be fixed by simply not caching when the list is too huge.

If it crashed after playing around with the app, well, I'm not sure why. But I'll still apply the fix I mentioned above and maybe you can try again once I've published it.

Thank you very much for your report.

**Comment by kuru-rin** [comment]
> Do you remember when you are trying with the Beta app: Did it crash directly without ever completely loading the list or did it manage to load the list and only crashed when there's an update?

If I go into "Anime List" it always crashes indeed, but it is loading about 10 seconds before it does so.
Even if I don't really do anything in the app at all, it crashes after about the same amount of time. 
(I assume it is just loading the list in the background? Then it all makes perfect sense)

> I think it can be fixed by simply not caching when the list is too huge.

Sounds great, thank you so much for your work!
