### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by brian6932** [zend10/AL-chan#153]
I updated to Android 14, and now whenever AL-chan's launched, I get this crash error.
I tried clearing the data and reinstalling, but it doesn't help, I did find that this error only occurs when logged in though.
```
FATAL EXCEPTION: main
Process: com.zen.alchan, PID: 11533
z9.c: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | g7.m
	at ca.a$i.accept(SourceFile:5)
	at ea.h.b(Unknown Source:13)
	at ha.r$a.f(Unknown Source:47)
	at ha.r$a.run(SourceFile:85)
	at w9.c$b.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8248)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: g7.m
	at z6.r0.t(SourceFile:114)
	at z6.j1$a.a(Unknown Source:6)
	at w7.b0.g(SourceFile:13)
	at k7.i.c(Unknown Source:11)
	at w7.g.f(SourceFile:215)
	at k7.f.H(SourceFile:11)
	at androidx.fragment.app.i0.r(SourceFile:46)
	at androidx.fragment.app.i0.k(SourceFile:69)
	at androidx.fragment.app.c0.A(SourceFile:25)
	at androidx.fragment.app.c0.S(Unknown Source:81)
	at androidx.fragment.app.c0.z(SourceFile:32)
	at androidx.viewpager2.adapter.FragmentStateAdapter.q(SourceFile:162)
	at androidx.viewpager2.adapter.FragmentStateAdapter.k(SourceFile:3)
	at androidx.recyclerview.widget.b.a(SourceFile:44)
	at androidx.recyclerview.widget.RecyclerView$n.m(SourceFile:267)
	at androidx.recyclerview.widget.LinearLayoutManager.h1(SourceFile:34)
	at androidx.recyclerview.widget.LinearLayoutManager.U0(SourceFile:54)
	at androidx.recyclerview.widget.LinearLayoutManager.n0(SourceFile:838)
	at androidx.recyclerview.widget.RecyclerView.r(SourceFile:87)
	at androidx.recyclerview.widget.RecyclerView.p(SourceFile:123)
	at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:8)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at androidx.viewpager2.widget.ViewPager2.onLayout(Unknown Source:60)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at androidx.appcompat.widget.LinearLayoutCompat.onLayout(SourceFile:168)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:789)
	at android.view.View.layout(View.java:24432)
	at android.view.ViewGroup.layout(ViewGroup.java:6443)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4455)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3767)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2650)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9526)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1343)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
	at android.view.Choreographer.doFrame(Choreographer.java:882)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1326)
	... 8 more
```

**Comment by brian6932** [comment]
This was actually due to a Kernel incompatibility with my ROM 😅
